allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@inflowenger/flow-trace@0.2.0'
  - '@inflowenger/flow-trace@0.2.1'
  - '@inflowenger/plugin-form-builder@0.1.4'
  - '@inflowenger/plugin-form-builder@0.1.6'
  - '@inflowenger/plugin-form-builder@0.1.7'
  - '@inflowenger/plugin-form-builder@0.1.8'
  - '@inflowenger/plugin-form-builder@0.1.9'
  - '@inflowenger/plugin-form-builder@0.2.0'
  - '@inflowenger/flow-trace@0.2.2'
